import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { saveBGWalkthrough } from '../supabase/services';
import { BG_ZONES, BG_ZONE_ORDER, SLA_TIERS } from '../data/bgZones';

export const BGComplete = ({ bgWalkthrough }) => {
  const navigate = useNavigate();
  const [saving, setSaving] = useState(true);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState(null);
  const [emailSent, setEmailSent] = useState(false);

  const {
    getWalkthroughData,
    resetWalkthrough
  } = bgWalkthrough;

  const walkthroughData = getWalkthroughData();

  // Save walkthrough on mount
  useEffect(() => {
    const saveData = async () => {
      try {
        setSaving(true);
        setError(null);

        // Save to Supabase
        await saveBGWalkthrough(walkthroughData);
        setSaved(true);

        // Send email summary
        await sendEmailSummary(walkthroughData);
        setEmailSent(true);

      } catch (err) {
        console.error('Error saving B&G walkthrough:', err);
        setError(err.message || 'Failed to save walkthrough');
      } finally {
        setSaving(false);
      }
    };

    saveData();
  }, []);

  // Generate email summary
  const sendEmailSummary = async (data) => {
    // In a real implementation, this would call an API endpoint
    // For now, we'll just log what would be sent
    console.log('Email would be sent to:', data.auditorEmail);
    console.log('Email content:', generateEmailContent(data));

    // Simulate API call
    await new Promise(resolve => setTimeout(resolve, 500));
    return true;
  };

  const generateEmailContent = (data) => {
    const greenCount = Object.values(data.zoneRatings || {}).filter(r => r === 'GREEN').length;
    const amberCount = Object.values(data.zoneRatings || {}).filter(r => r === 'AMBER').length;
    const redCount = Object.values(data.zoneRatings || {}).filter(r => r === 'RED').length;

    let content = `
WEEKLY B&G WALKTHROUGH REPORT
=============================
Campus: ${data.campus}
Date: ${data.date}
Time: ${data.time}
Auditor: ${data.auditor}
Duration: ${data.duration || 'N/A'} minutes

CAMPUS RATING: ${data.campusRating || 'N/A'}
=============================

ZONE SUMMARY:
- GREEN: ${greenCount}
- AMBER: ${amberCount}
- RED: ${redCount}

`;

    if (data.issues?.length > 0) {
      content += `\nISSUES FOUND (${data.issues.length}):\n`;
      content += '-----------------------------\n';

      // Group by tier
      const tier1 = data.issues.filter(i => i.tier === 1);
      const tier2 = data.issues.filter(i => i.tier === 2);
      const otherTiers = data.issues.filter(i => i.tier > 2);

      if (tier1.length > 0) {
        content += `\nTIER 1 - CRITICAL (${SLA_TIERS[1].resolution}):\n`;
        tier1.forEach(issue => {
          content += `  • ${issue.zoneName}: ${issue.checkText}\n`;
          if (issue.notes) content += `    Notes: ${issue.notes}\n`;
        });
      }

      if (tier2.length > 0) {
        content += `\nTIER 2 - HIGH-VISIBILITY (${SLA_TIERS[2].resolution}):\n`;
        tier2.forEach(issue => {
          content += `  • ${issue.zoneName}: ${issue.checkText}\n`;
          if (issue.notes) content += `    Notes: ${issue.notes}\n`;
        });
      }

      if (otherTiers.length > 0) {
        content += `\nTIER 3/4 - ROUTINE:\n`;
        otherTiers.forEach(issue => {
          content += `  • ${issue.zoneName}: ${issue.checkText}\n`;
          if (issue.notes) content += `    Notes: ${issue.notes}\n`;
        });
      }
    }

    if (data.observations?.length > 0) {
      content += `\nOBSERVATIONS ROUTED TO OTHER PILLARS (${data.observations.length}):\n`;
      content += '-----------------------------\n';
      data.observations.forEach(obs => {
        content += `  • ${obs.categoryName} → ${obs.pillar}\n`;
        content += `    ${obs.description}\n`;
      });
    }

    content += `\n-----------------------------\n`;
    content += `Report generated by Alpha Facilities App\n`;

    return content;
  };

  const handleDone = () => {
    resetWalkthrough();
    navigate('/');
  };

  const handleViewHistory = () => {
    resetWalkthrough();
    navigate('/bg/history');
  };

  return (
    <div style={{
      minHeight: '100vh',
      background: walkthroughData.campusRating === 'PASS'
        ? 'linear-gradient(180deg, #059669 0%, #047857 100%)'
        : 'linear-gradient(180deg, #dc2626 0%, #b91c1c 100%)',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '40px 20px'
    }}>
      {/* Status Icon */}
      <div style={{
        width: '120px',
        height: '120px',
        borderRadius: '50%',
        backgroundColor: 'rgba(255,255,255,0.2)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: '24px'
      }}>
        {saving ? (
          <div style={{ fontSize: '48px' }}>⏳</div>
        ) : error ? (
          <div style={{ fontSize: '48px' }}>⚠️</div>
        ) : (
          <div style={{ fontSize: '48px' }}>
            {walkthroughData.campusRating === 'PASS' ? '✅' : '📋'}
          </div>
        )}
      </div>

      {/* Title */}
      <h1 style={{
        color: '#fff',
        fontSize: '28px',
        fontWeight: '700',
        marginBottom: '8px',
        textAlign: 'center'
      }}>
        {saving
          ? 'Saving Walkthrough...'
          : error
          ? 'Error Saving'
          : 'Walkthrough Complete!'}
      </h1>

      {/* Subtitle */}
      <p style={{
        color: 'rgba(255,255,255,0.9)',
        fontSize: '18px',
        marginBottom: '32px',
        textAlign: 'center'
      }}>
        {saving
          ? 'Please wait...'
          : error
          ? error
          : `Campus ${walkthroughData.campusRating || 'Rating'}`}
      </p>

      {/* Summary Card */}
      {!saving && !error && (
        <div style={{
          backgroundColor: '#fff',
          borderRadius: '16px',
          padding: '24px',
          width: '100%',
          maxWidth: '320px',
          marginBottom: '32px'
        }}>
          <div style={{ textAlign: 'center', marginBottom: '20px' }}>
            <div style={{ fontSize: '14px', color: '#666', marginBottom: '4px' }}>Campus</div>
            <div style={{ fontSize: '20px', fontWeight: '700', color: '#092849' }}>
              {walkthroughData.campus}
            </div>
          </div>

          <div style={{
            display: 'grid',
            gridTemplateColumns: '1fr 1fr 1fr',
            gap: '12px',
            marginBottom: '20px'
          }}>
            <div style={{ textAlign: 'center' }}>
              <div style={{
                fontSize: '24px',
                fontWeight: '700',
                color: '#10b981'
              }}>
                {walkthroughData.greenZones || 0}
              </div>
              <div style={{ fontSize: '12px', color: '#666' }}>Green</div>
            </div>
            <div style={{ textAlign: 'center' }}>
              <div style={{
                fontSize: '24px',
                fontWeight: '700',
                color: '#f59e0b'
              }}>
                {walkthroughData.amberZones || 0}
              </div>
              <div style={{ fontSize: '12px', color: '#666' }}>Amber</div>
            </div>
            <div style={{ textAlign: 'center' }}>
              <div style={{
                fontSize: '24px',
                fontWeight: '700',
                color: '#ef4444'
              }}>
                {walkthroughData.redZones || 0}
              </div>
              <div style={{ fontSize: '12px', color: '#666' }}>Red</div>
            </div>
          </div>

          <div style={{
            borderTop: '1px solid #e5e7eb',
            paddingTop: '16px'
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
              <span style={{ color: '#666', fontSize: '14px' }}>Issues Found</span>
              <span style={{ fontWeight: '600', fontSize: '14px' }}>
                {walkthroughData.totalIssues || 0}
              </span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
              <span style={{ color: '#666', fontSize: '14px' }}>Observations</span>
              <span style={{ fontWeight: '600', fontSize: '14px' }}>
                {walkthroughData.totalObservations || 0}
              </span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span style={{ color: '#666', fontSize: '14px' }}>Duration</span>
              <span style={{ fontWeight: '600', fontSize: '14px' }}>
                {walkthroughData.duration ? `${walkthroughData.duration} min` : 'N/A'}
              </span>
            </div>
          </div>

          {/* Email Status */}
          <div style={{
            marginTop: '16px',
            padding: '12px',
            backgroundColor: emailSent ? '#f0fdf4' : '#f3f4f6',
            borderRadius: '8px',
            display: 'flex',
            alignItems: 'center',
            gap: '8px'
          }}>
            <span style={{ fontSize: '20px' }}>
              {emailSent ? '✉️' : '⏳'}
            </span>
            <div style={{ fontSize: '14px', color: emailSent ? '#059669' : '#666' }}>
              {emailSent
                ? `Report sent to ${walkthroughData.auditorEmail}`
                : 'Sending email report...'}
            </div>
          </div>
        </div>
      )}

      {/* Action Buttons */}
      {!saving && (
        <div style={{ width: '100%', maxWidth: '320px' }}>
          <button
            onClick={handleDone}
            style={{
              width: '100%',
              padding: '18px',
              borderRadius: '12px',
              fontSize: '18px',
              fontWeight: '700',
              border: 'none',
              cursor: 'pointer',
              backgroundColor: '#fff',
              color: '#092849',
              marginBottom: '12px'
            }}
          >
            Done
          </button>

          {error && (
            <button
              onClick={() => window.location.reload()}
              style={{
                width: '100%',
                padding: '16px',
                borderRadius: '12px',
                fontSize: '16px',
                fontWeight: '600',
                border: '2px solid rgba(255,255,255,0.3)',
                cursor: 'pointer',
                backgroundColor: 'transparent',
                color: '#fff'
              }}
            >
              Retry
            </button>
          )}
        </div>
      )}
    </div>
  );
};
